In [ ]:
import numpy as np
print(np.array([1,2,3,5]))

[1 2 3 5]


In [ ]:
import numpy as np

In [ ]:
A1=np.array([1,2,3,4])
print(A1)

[1 2 3 4]


In [ ]:
A1.size

4

In [ ]:
A2=np.array([[1,2,3,4],[5,6,7,8]])
print(A2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.shape

(2, 4)

In [ ]:
A2.size

8

In [ ]:
A2.ndim

2

In [ ]:
A3=np.array([[[1,2,3,],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
type(A3)

numpy.ndarray

In [ ]:
A3.shape

(1, 3, 3)

In [ ]:
A3.size

9

In [ ]:
A3.ndim

3

In [ ]:
import numpy as np
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
z1.shape


(3,)

In [ ]:
type(z1)

numpy.ndarray

In [ ]:
z1.size

3

In [ ]:
z1.ndim

1

In [ ]:
z2=np.zeros((2,3))
z2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2=np.zeros((2,3),dtype=int)
z2

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
z2.ndim

2

In [ ]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
type(z3)

numpy.ndarray

In [ ]:
z3.ndim

3

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
z3.size

24

In [ ]:
import numpy as np
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
a1=np.ones(3,dtype=int)
a1

array([1, 1, 1])

In [ ]:
a1.shape

(3,)

In [ ]:
a1.size

3

In [ ]:
a1.ndim

1

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2=np.ones((3,4))
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a2=np.ones((3,4),dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
type(a2)

numpy.ndarray

In [ ]:
a2.shape

(3, 4)

In [ ]:
a2.ndim

2

In [ ]:
a2.size

12

In [ ]:
a3=np.ones((4,2,3))
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a3=np.ones((4,2,3),dtype=int)
a3

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [ ]:
import numpy as np
#1d full array
f1=np.full(3,9)
f1

array([9, 9, 9])

In [ ]:
f2=np.full((2,3),9)
f2

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
f3=np.full((4,2,3),10)
f3

array([[[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10]]])